src/components/DirectionsNullState.js

it's open-source now, let's tell everyone!

link source code

---

src/lib/geometry.js

Definitions:
Steep: 8%
Very steep: 14%
Based on the maximum grade measured over any 500' length
Fixes #173
Future work:
- Ultimately remove the grade percentages. I'm erring on the side of including more info as we test this feature out and assess whether my definitions and 500' threshold work well.
- "Steep hill" should not be colored green. Maybe a gray pill.
- Indicate steep hills visually on the map.
- Show elevation profiles for legs (or entire routes).

label steep hills in instructions

---

package-lock.json
package.json
src/components/SearchBar.js
src/components/TimeBar.js
src/features/routeParams.js
src/features/routes.js
src/lib/describePlace.js
src/lib/urlMiddleware.js
src/store.js

- does not yet support back button
- does preserve the name of the locations
- does preserve time of departure/arrival

basic support for routes in URL

---

src/lib/BikehopperClient.js

Starting the work for #198.
Checks a window.debug flag and returns edges if that is true

Check window.debug to return edges

---

src/components/DirectionsNullState.js

note we only support Bay Area

---

src/components/BikehopperMap.js

This PR removes the road-name labelling that we manually inserted in our route line styles, and replaces that functionality by changing the layer order such that the road-name labels from the basemap now display over our route line.
This makes our labels much shorter, since it doesnt have to make a long label like `shared lane ( Shotwell St )` anymore, instead mapblibre-gl displays `Shotwell St` label wherever it wants to, and our `shared lane` label shows up wherever theres free space.
In orderto make this look good though I had to increase the size of the  `mapbox-streets` road-labels by a 2pt 's. Inorder to do that elegantly, I had to copy over the existing expression and increase the values by 2. So we have some `mapbox-streets-v11` dependent stuff hardcoded into our codebase with …

Switch layer order so that road labels in basemap display over route line

---

src/components/ItineraryBikeStep.js

Reasonable icon (I don't love it but it's an improvement)
Bolding
Fixes #217

Improve roundabout directions

---

src/lib/urlMiddleware.js

I've been told I should do this. *shrug*

wrap localstorage uses in try-catch

---

src/lib/urlMiddleware.js

This has been annoying me: whenever I open BikeHopper on my phone it reloads some old route that I was looking at yesterday or maybe weeks ago, forcing me to clear out of that before I can get new directions.
My solution to #226 was too eager. We do want to restore routes when the app pages out of memory and you're still on the trip, but not restore super old routes.
This makes the maximum age 1 hour for a route to be restored like this. Note that the 1 hour timer will be reset each time the app pages out of memory and is restarted.

Don't restore OLD routes when PWA

---

vite.config.js

API moved to /api/v1 from /v1 in https://github.com/bikehopper/bikehopper-web-app/pull/22, proxy needs update

Update proxy api route

---

src/components/MapPlusOverlay.jsx
src/features/geolocation.js
src/features/routeParams.js

Fixes #272 
Also, show a spinner when geolocating you. Fixes one of the remaining bullet points in #184

Navigate from current location when "Directions to" selected

---

src/components/BikehopperMap.jsx

i don't even know how/why i changed this

fix shared lane color

---

src/components/SearchAutocompleteDropdown.jsx

I broke using the X to remove a recently used location from the list in #303.

fix recent location x-out

---

src/features/routeParams.js

Fix "directions from"

---

src/components/BikehopperMap.jsx
src/components/ItineraryBikeStep.jsx
src/lib/geometry.js
tailwind.config.js

...and render as pills in the itinerary.
Fixes #333
Fixes #334
Addresses the first two tasks in #177

Localize bike infra annotations

---

package-lock.json

I forgot to put this in the pull request for this feature.

Add package-lock.json for fit file feature

---

package-lock.json
package.json
vite.config.ts

The TSC output was overwriting the vite output in the terminal. its not clear to me what this checker even did since everything worked without it.
https://github.com/bikehopper/bikehopper-ui/issues/347

Remove vite-plugin-checker

---

src/features/routeParams.js

It wasn't automatically routing from the current location due to a mistake in 8b9ded0a0716243f5bd4a49430f94f65996bf8a7
Fixes #361

Fix select end point on map

---

README.md
index.html
src/components/BikeHopperMap.css
src/components/BikeHopperMap.tsx
src/components/MapPlusOverlay.jsx
src/components/PlaceIcon.tsx
src/components/ShareFit.tsx
src/features/geocoding.ts
src/features/routeParams.ts
src/features/routes.ts
src/features/storage.ts
src/lib/BikeHopperClient.ts
src/lib/describePlace.ts

We mostly do this, and the exceptions keep tripping me up.

Consistently capitalize H in BikeHopper

---

package-lock.json

fixes https://github.com/advisories/GHSA-gcx4-mw62-g8wm

upgrade Rollup

---

src/components/BikeHopperMap.tsx

Also change mouse cursor on desktop.
Fixes #38. Thank you @arindam1993 for suggesting this approach.

Increase tap/click target for routes on map

---

src/components/ItineraryHeader.tsx

Fixes #401.
Before:
[Screencast from 12-20-2024 05:52:05 PM.webm](https://github.com/user-attachments/assets/ace6b865-0cb2-49ef-a4d2-52fceb9a9fcb)
After:
[Screencast from 12-20-2024 06:00:35 PM.webm](https://github.com/user-attachments/assets/d6ece20f-f542-42fd-aa10-eee1024ca9a9)

Limit un-expanded alerts to one line

---

src/components/DesktopMapLayout.tsx
src/components/MobileMapLayout.css
src/components/MobileMapLayout.tsx
tailwind.config.js

It looks a bit nicer and matches mobile.

Give desktop sidebar a shadow

---

src/lib/urlMiddleware.js

As suggested to clean up the URL share.

Limit lng-lat in URL to 5 points
