bikehopper/bikehopper-ui

- src/features/geocoding.js
- src/features/routes.js
- src/lib/BikehopperClient.js
Fixes #166
Tested via:
1. Find a departure time when the still unfixed router issue bikehopper/graphhopper#87 will cause GraphHopper to consistently 500. When requesting such a route, the alert says "Server error"
2. Shut down local dev server so the localhost proxy will not be reachable and fetch a route. Alert says "Can't connect to server"
3. After restarting local dev server fetch a route to the Greater Farallones Marine Sanctuary. Alert says "Can't find a route"
Geocoding errors:
4. With local dev server shut down (as in test case 2) attempt to geocode a new location string. Alert says "Can't connect to server"
5. With local dev server back up, try to geocode gibberish. Alert says "Can't find hgdsds crjgjefwe"
Missing test case: I'm not currently aware of a geocoding string that will …
> Correct error msgs when server 500s

- src/components/App.js
- src/components/MapPlusOverlay.css
- src/components/MapPlusOverlay.js
In my haste to get the scrolling bottom drawer working a while back, I put a bunch of crap into the App component that handled scrolling, positioning the map controls, forwarding touch events and stuff like that.
This was all mixed in with the top-level logic of what content to render in the top bar and bottom drawer, depending on global application state.
This commit splits that out. <App> decides what content to render at the top and bottom based on app state, while the new <MapPlusOverlay> handles the mechanics of the map overlay, scrolling, touch events, etc.
In case it's not obvious, all of the code in MapPlusOverlay here is not new code, but is moved from App with no changes except to rename CSS classes.
> split Map + Overlay management out of <App>

- src/components/SearchAutocompleteDropdown.js
- src/components/SearchBar.js
- src/features/routeParams.js
This is a fix for issue #103, description copied below for reference:
>  1. Enter a start and end location and fetch routes
>  2. Tap into one of the location input boxes
>  3. Decide that you actually don't want to edit the location, but want
>  to go back to the routes already fetched
>
> This currently isn't possible. If you tap the back button in this state, it won't return you to the routes you had, but instead, clear everything out.
This implements more or less the strategy I described in a comment on that issue:
> If:
>
>   * you blur a location input,
>   * and not by focusing the other location input,
>   * nor by tapping on a location in the dropdown,
>   * and you didn't change the input you just blurred,
>   * and we already have routes,
>
> Then we should set editingLocation: …
> Make it possible to cancel a location edit

- package-lock.json
- package.json
- src/components/SearchAutocompleteDropdown.js
- src/features/geocoding.js
This is inspired by and partially mitigates issue #192, where a geocoding search for "Lands End" produced mysterious and questionable results.
I don't consider the issue to be solved by this but it helps somewhat by giving more results and a visual indication of what kind of place you're being directed to.
Example 1:
Example 2:
This is kind of messy and incomplete, and could be worked on more, but maybe it's worth merging in and iterating on? Open to feedback.
> More search results and custom icons

- src/components/AlertBar.css
I was using the alert bar for debugging and printed a long string with a URL in it and it made the "X" go offscreen so I couldn't dismiss the alert. This prevents that from happening. Shouldn't even come up with real alerts
> alert bar: hide horizontal overflow

- src/components/SelectionListItem.js
I introduced a bug in PR #195 ("make it possible to cancel a location edit") on iPhone. The bug:
1. Get routes between two geocoded locations
2. Tap on starting location
3. Tap "Current Location"
Expected: BikeHopper geolocates you (asking permission if needed) then routes from current location to the previously entered destination
Actual: The autocomplete goes away, the previously entered start point stays the same and the previously fetched routes stay
This was happening because when you tapped an autocomplete result, Safari set the event.relatedTarget of the blur event to null, whereas I rely on relatedTarget being the <a href="..." ...> of the autocomplete result.
I'm working around this by setting a tabindex on the <a>, which causes Safari to think that it can be focused.
This is not …
> fix changing locations from autocomplete on iPhone

- src/components/DirectionsNullState.js
- src/components/Itinerary.js
- src/components/ItineraryTransitLeg.js
- src/features/viewport.js
- src/lib/region/BayArea.js
- src/lib/region/index.js
I wanted to start isolating all the Bay Area-specific stuff in the frontend to get a jump on supporting other regions in the future
This puts all the Bay Area stuff in the frontend (AFAIK) into lib/region/BayArea.js and we could in the future add lib/region/DC.js, lib/region/Barcelona.js, etc. (Possibly not with this exact architecture, because I don't think we can conditionally import ES modules, but we'll cross that bridge when we come to it)
> split out Bay Area-specific constants, etc to region dir

- src/components/ItineraryTransitLeg.js
- src/components/RoutesOverview.js
This is a workaround for a GraphHopper bug. GraphHopper is incorrectly dropping the route_name if the GTFS (legally!) defines only a route_long_name and not a route_short_name, as CTA does for its Red Line (for instance).
So, without this, the name of the Red Line in Chicago transit instructions utilizing it is missing, and there's a blank space.
See: https://github.com/bikehopper/graphhopper/issues/110
> Show transit route_id if route_name not defined

- src/features/routeParams.js
Fixes #210 
Ran into this while trying to use BikeHopper in Chicago without geocoding support. My workaround via the URL was breaking when BikeHopper would re-geocode the locations and get northern California results
> Don't re-geocode locations hydrated from a URL

- src/components/ItineraryHeader.js
- src/components/ItineraryTransitLeg.js
Up until now we have always shown a bus icon for every transit leg, even if it is BART, Muni light rail, a ferry, etc., and we've used the generic word "line" ("Ride the N line").
The route type is actually provided for us in GTFS though. See the spec: https://gtfs.org/schedule/reference/#routestxt
But GraphHopper hasn't been patching route_type through in its responses. That will be fixed by
https://github.com/bikehopper/graphhopper/pull/111
This commit uses the route_type, if present, to display the correct icon and a more specific noun ("Ride the N train"). When this and the above router change are both merged and deployed, this will fix #206.
> Show correct transit type & icon (bus, tram, train, etc)

- src/components/Itinerary.js
- src/components/ItineraryBikeLeg.js
- src/components/ItineraryHeader.js
- src/components/ItineraryTransitLeg.js
- src/components/RouteLeg.css
- src/components/RouteLeg.js
- src/components/RoutesOverview.js
- src/lib/modeDescriptions.js
I received feedback from my designer cousin that it's hard to tell what "Bike, 5, Bike" means. We should say in the routes overview at a glance that that means the 5 bus. And so on, train icon for BART "Red-N", etc.
An example:
An example with a ferry: (it was hard to make it use ferry, I guess this ferry is slow)
We already have code (recently added by me, used in the itinerary) to select an icon based on the GTFS route type, so this moves that code around so it can be used twice.
> mode icon in route summary

- src/components/Itinerary.js
- src/components/ItineraryBikeLeg.js
- src/components/ItineraryBikeStep.js
- src/components/ItineraryRow.js
- src/components/ItineraryStep.js
- src/components/ItineraryTransitLeg.css
- src/components/ItineraryTransitLeg.js
- src/components/MapPlusOverlay.css
- src/components/Routes.js
- src/hooks/useScrollToRef.js
In the itinerary you can click on a transit stop ("24th St Mission station") or a specific bicycle direction ("Turn left on 24th Street") to view that step/stop in isolation.
This commit makes it so, when you then go back, the step/stop you were viewing is centered, so you don't lose your place in the overall itinerary.
Fixes #218
> Preserve scroll pos when exiting single-step view

- src/components/BikehopperMap.js
- src/features/misc.js
- src/lib/pwa.js
- src/lib/urlMiddleware.js
BikeHopper is supposed to save route params in the URL so it can fetch the routes you were last viewing (or, similar routes but for the current time) if the page is reloaded, or freed from memory on a phone.
This fixes 2 situations where that didn't work
- Sporadically, on desktop browsers; the feature was flaky
- When installed as a progressive web app (saved to home screen)
See the individual commit messages for details.
> Fixes to restore last viewed routes when app pages out of memory

- src/features/geolocation.js
Before:
> Can't geolocate: permission denied
- Unclear who's denying the permission
- Jargon-y term "geolocate" may not be understood. Are we telling them they're not allowed to navigate to the coffee shop they typed in or whatever?
Proposed:
> Your browser isn't letting BikeHopper detect your current location. Check your browser settings for this website.
- Makes it clear where the problem lies and how to resolve
- Uses the same terminology used elsewhere in app ("current location") rather than technical jargon ("geolocate")
Fixes #190
> Friendlier geolocation error msgs

- src/components/MapPlusOverlay.css
- src/components/RoutesOverview.css
- src/components/RoutesOverview.js
- src/components/SearchAutocompleteDropdown.js
- src/components/SelectionListItem.css
- src/components/SelectionListItem.js
This is a refactor, small a11y improvement, and small visual enhancement, motivated by work I'm doing on a different branch but reviewable on its own.
Motivation: I'm adding storage of recently used locations so you can easily find directions again to a place you just looked up. Thus, I want to add an X-out so you can delete a place you don't want showing up in that list.
This PR doesn't do that however. It:
1. Simplifies `SelectionListItem`, which was using two different versions of markup depending on whether the item was clickable or not. But it's a _selection_ list, so the items are always supposed to be clickable.
2. Makes `SelectionListItem` use a `<button>` instead of a link. This is better for a11y.
3. Removes the one non-clickable usage of `SelectionListItem`: the warning for …
> Simplify SelectionListItem + fix rounded borders

- src/components/PlaceIcon.js
- src/components/SearchAutocompleteDropdown.js
- src/components/SearchBar.js
Status quo: If we have a relevant custom icon for a feature (e.g. steaming coffee mug for a cafe, tree icon for a park), we display that icon in the autocomplete drop down instead of a pin. But we still always use the generic pin icon in the search bar itself.
This commit: Uses the custom icon, if any, in the search bar itself for geocoded features. It will be replaced with a generic pin icon if the location text is subsequently edited.
Limitation of this commit: If the location is hydrated from the URL (reload page or follow link), the custom icon will be lost because in that case we only have the place name and coordinates, not further details.
> Use custom place icons in search bar

- src/components/SearchAutocompleteDropdown.js
- src/components/SelectionListItem.css
- src/components/SelectionListItem.js
- src/features/geocoding.js
- src/features/routeParams.js
- src/features/storage.js
- src/lib/urlMiddleware.js
- src/store.js
This saves recently looked-up locations to LocalStorage. This will fix one of the biggest pain points in our app where if you back out of directions by mistake, and want to get them back, you have to start over completely.
Up to 8 locations are saved, they're saved for up to just over a week, and you can X them out to remove them.
As part of this change, the geocoding reducer caches typeahead locations differently: The typeahead cache only contains OSM IDs, while a separate cache maps OSM IDs to hashes of place properties. Also, deduping multiple Photon results with the same OSM ID now happens in the reducer, not in the autocomplete component.
Possible future work:
- When Photon gives us the same OSM ID with two different osm_key/osm_value pairs, save both (could help with classification …
> Recent locations

- src/components/SelectionListItem.js
I noticed in the inspector that SelectionListItem buttons had the class name "undefined." No user impact, but it was goofy so here's a fix.
> Fix "undefined" class names

- src/features/routeParams.js
Today while out and about using BikeHopper, I noticed that when I changed my plans along the way and changed my destination, the "Current Location" start point of the route provided was stale.
This looks like a bug in `locationsSubmitted`. It's always falling back to a `point` if present, which it should do for Custom points or geocoded points, but for "Current Location," we should always geolocate, relying on the browser's caching (via the `maximumAge` param and the value provided for that in `features/geolocation.js`).
With this change, any time you fetch a new route, your "Current Location" will be updated first.
> Always refresh current location for route fetch

- compile-langs.sh
- compiled-lang/en.json
- compiled-lang/es.json
- config/paths.js
- config/webpack.config.js
- lang/en.json
- lang/es.json
- package-lock.json
- package.json
- src/components/App.js
- src/components/DirectionsNullState.js
- src/index.js
Contains 3 translatable strings, 1 of which ("Get directions") I translated to Spanish based on Wiktionary and it may be wrong.
The translation may be tested by adding `?locale=es` to the end of the BikeHopper URL.
To extract default messages:
npm run extract
To compile translations:
./compile-langs.sh
TODO:
- add lint rules https://formatjs.io/docs/guides/develop#linter-installation
- integrate with translation tooling https://formatjs.io/docs/getting-started/application-workflow#pipeline
- translate more messages + numbers
Relevant to #238
> Basic i18n support

- src/components/SearchAutocompleteDropdown.js
- src/components/SearchBar.js
- src/components/SelectionListItem.js
I noticed that on my iPhone, when I have routes, but I want to go back and select a different autocomplete result (or "Current Location") from one of the dropdowns, it wasn't working. It just exits the search bar.
This is apparently because my solution for #103, the longstanding issue to make it easier to cancel a location edit, never worked on mobile Safari. When editing locations and the search bar is blurred, and nothing has changed, we exit out of the whole search bar on purpose to restore the routes you were looking at. Unless, that is, the search bar was blurred by focusing an autocomplete result.
But in mobile Safari, <button>s do not receive focus, so the event.relatedTarget was null.
I've hacked around this via the insight on this Stack Overflow answer that mousedown events occur …
> Fix selecting secondary dropdown result on iOS

- .eslintrc
- package-lock.json
- package.json
- src/components/DirectionsNullState.js
See: https://formatjs.io/docs/tooling/linter/
I turned on rules that seem to make sense for the default case
- Enforce defaultMessage so stuff doesn't show up blank at first
- Enforce description to provide context for translators
- Let IDs be autogenerated as FormatJS recommends
- Avoid too-complicated message variants
I didn't turn on the one banning literal strings in JSX, yet, but once every message is internationalized, we could to prevent accidentally not translating something. We would want to add exceptions for deliberately untranslated things like the BikeHopper project name.
> Add FormatJS lint rules

- src/lib/describePlace.js
I was looking up Mountain View Cemetery and... what? It has a zip code of 5000?
Turns out, on OSM it has an addr:housenumber but no addr:street.
I am fixing this on OSM for this particular POI but we shouldn't display housenumbers without streets.
> Don't display address numbers without street names

- src/components/ItineraryHeader.css
- src/components/ItineraryHeader.js
- src/components/ItineraryTransitLeg.js
- src/components/RouteLeg.css
- src/components/RouteLeg.js
- src/components/RoutesOverview.js
Basic implementation of service alert display. Requires this Bikehopper-web-app pull request to be merged and deployed first, or else it won't do anything:
https://github.com/bikehopper/bikehopper-web-app/pull/17
Examples in route overview. Notice the warning triangle next to the (AC Transit) L and 76, which have alerts that apply to them:
Examples in itinerary. Unfortunately AC Transit's alerts are spammy and have all three languages jammed into one string instead of being properly translated, but that's what we've got to work with. Imagine actually useful alerts appearing in this space instead:
> Display alerts in itineraries and route overviews

- src/components/TimeBar.js
- src/lib/urlMiddleware.js
Another annoyance fix.
When you switch departure from "Now" to "Depart at" or "Arrive by," the datetime input should initialize to either the current time or 2 hours from now respectively. This was broken because `<input type="datetime-local">` only accepts values in this bespoke format:
2018-06-12T19:30
and was being passed UNIX timestamps (number of ms since epoch) instead.
I've also changed the code to always keep normal timestamps in the Redux store, and use the bespoke string format only within TimeBar.
> Fix: Initialize datetime input properly

- src/components/SearchAutocompleteDropdown.jsx
Fixes #243. Restating the repro steps described there:
1. Type "reveille," all the different Cafe Reveille locations come up
2. Select the top one [say Polk St]. Then tap into destination box again. You get the same list of Reveilles again.
3. Select the second from top [say Long Bridge St]. Tap into destination box again.
You should get the same list a third time and be able to select a third Reveille location and so on, but there were no results. This commit fixes this issue.
The key is that the "fromInputText" attribute in the "select geocoded location" action should not necessarily be the *current* input text, but rather the original input text that produced the list of geocoded locations being selected from.
> Fix serial selection of different autocompletes

- compiled-lang/en.json
- lang/en.json
- src/components/ItineraryBikeLeg.jsx
- src/components/ItineraryHeader.jsx
- src/components/ItineraryTransitLeg.jsx
- src/components/RouteLeg.css
- src/components/RouteLeg.jsx
- src/components/RoutesOverview.jsx
- src/lib/BikehopperClient.js
Here's a quick and dirty solution for warning when routes have steps (#263). It borrows the icon we use for transit service alerts.
This also fixes alerts looking goofy if the header or body text is blank, seen in the wild in SFMTA alerts, part of issue #258.
- *Use a steps icon instead of the generic alert icon.* I [requested a steps icon](https://github.com/iconoir-icons/iconoir/issues/307) from the icon library we use, or we could also look for another compatibly-licensed icon collection that has one or draw our own.
- *Clean up the CSS, which is a bit weird.* I made it look properly aligned in Chrome and Firefox. I'll probably be restyling things using TailwindCSS pretty soon, so didn't want to spend much time fiddling with it.
> warn when bike legs have steps

- src/components/Itinerary.css
I removed this top: 4px rule from Icon itself and missed that it needed to be added back here
Broken
Fixed
> fix vertical alignment of "back to routes" icon

- compiled-lang/en.json
- lang/en.json
- package-lock.json
- package.json
- src/components/BikehopperMap.jsx
- src/components/SearchBar.jsx
- src/features/routeParams.js
...or right click on desktop.
MapLibre doesn't natively support long press, so we're using a timer.
Tested on iPhone Safari, and desktop on Firefox and Chrome, with and without touch emulation (note that you have to reload BikeHopper when enabling or disabling touch emulation). Not tested on Android.
Fixes #72
> Select start/end point on map via long press

- src/components/BikehopperMap.jsx
- src/components/MapPlusOverlay.jsx
- src/lib/touch.js
Apparently Chrome for Android, unlike Safari for iPhone, fires a series of touchmove events even when you've only moved your finger an imperceptible amount, so we were failing to detect any long-press events.
We already have code in the map overlay to see if a touch move is far enough not to consider it a "click," so I factored this out and reused it.
Not yet actually tested on Android. @abhumbla, can you check this out and see if it works for you?
Also, I discovered a bug where (on iPhone Safari) the context menu could trigger while dragging a marker around, so fixed that too.
> Fix long-press to select points on Android

- src/components/RoutesOverview.css
- src/components/RoutesOverview.jsx
This shows the ascent/descent for returned routes, if provided by the server (which requires https://github.com/bikehopper/graphhopper/pull/95 to be merged and deployed, or something like it), and if the ascent/descent exceed a threshold, i.e., if the route is not nearly flat.
> Show total elevation gain/loss for routes if available

- src/features/routeParams.js
Geocoding an address/place name is asynchronous. So is geolocating the user (it sometimes takes 20+ sec on my laptop). So after we hydrate locations by geocoding/geolocating, we should check to make sure the user hasn't changed them in the meantime, and avoid overwriting any changes.
Fixes #180
> Check locations are same after hydrating

- src/lib/BikehopperClient.js
* updates API path to go from api.bikehopper.com/ to bikehopper.org/api/
* update API to use generic paths instead of implementation specific paths (e.g. /photon -> /geocode)
currently on staging and working fine. https://staging.bikehopper.org/
> Update API paths

- src/components/App.jsx
This gives more space for viewing the itinerary
And avoids the pitfall of accidentally clicking the Back button, meaning to go out of the itinerary and back to the route list, but actually clearing the routes entirely.
> Fade top bar away when viewing detailed itinerary

- src/components/RouteOptionsDialog.jsx
@Andykmcc pointed out, it was too hard to tell which state was ON and which state was OFF. This hopefully helps. Here's what it looks like with this PR, with trains deselected, and buses and ferries selected:
And in dark mode (not yet supported app-wide, but I've been building in support in new dialog boxes):
> Connecting modes: Make it clearer which state is ON

- src/components/App.jsx
I forgot to account for the map top controls in #297, causing this:
This is kind of a hacky fix. A prop is passed in which isn't actually used, but it forces a re-render, so the `useLayoutEffect` in `MapPlusOverlay` recomputes the position of the map top controls.
> Fix map controls getting stuck when top bar hides

- src/components/SearchAutocompleteDropdown.jsx
- src/features/geocoding.js
- src/features/storage.js
Geocoding results can be a node, way, or relation. Just using the OSM ID alone is ambiguous, as the node with ID 100 (say) has nothing to do with the way with ID 100, etc.
This commit solves the issue by using strings that begin with "N", "W", or "R", followed by a stringified ID, everywhere OSM IDs are used as a key. The format used to save recently-used locations in localStorage does not change. Fixes #302
> Store OSM IDs with type attached

- src/components/SearchAutocompleteDropdown.jsx
- src/features/geocoding.js
Several improvements to the search autocomplete:
1. Shows loading spinner while fetching suggestions
2. Shows an explicit "Nothing found" message if nothing is found, rather than staying blank
3. Keeps stale suggestions while fetching new ones (more below)
Why do this? Try this:
1. With the default Bay Area-wide viewport, type: 701 ala
2. Wait for results
3. Clear out of inputs
4. Zoom to just SF
5. Again type 701 ala
Behavior before this commit:
1. While waiting 700ms to debounce, you see stale results
2. Geocode request kicks off ("geocode_attempted"). Results disappear
3. Geocode request succeeds ("geocode_succeeded"). New results appear
On a fast connection this looks like results flickering away for no good reason.
With this commit, you see the stale results at both steps 1 & 2, …
> Autocomplete: "no results found," spinner, etc

- src/components/SearchAutocompleteDropdown.jsx
I messed up in PR #310 and accidentally displayed spinners in two cases where we don't actually fetch results:
1. When the location string derives from a geocode and we show other geocodings of the original string
2. When the location is loaded from URL parameters
> Fix some spurious loading spinners in autocomplete

- src/components/AlertBar.jsx
- src/components/DirectionsNullState.jsx
- src/components/Icon.css
- src/components/Itinerary.jsx
- src/components/ItineraryHeader.jsx
- src/components/ItineraryStep.jsx
- src/components/PlaceIcon.jsx
- src/components/RouteLeg.jsx
- src/components/RouteOptionsDialog.jsx
- src/components/RoutesOverview.jsx
- src/components/SearchAutocompleteDropdown.jsx
- src/components/SearchBar.jsx
- src/components/SelectionListItem.jsx
- src/components/TimeBar.jsx
- src/components/primitives/Icon.jsx
- src/components/primitives/ModalDialog.jsx
- tailwind.config.js
Converts `<Icon>` component to TailwindCSS and moves it to the primitives directory
> tailwindify Icon and move to primitives

- src/components/App.jsx
Fixes #318. The sense of the default state of this variable was reversed, causing this bug to happen the very first time the top bar faded away in a session.
> Fix mispositioned control after top bar fades

- src/components/PlaceIcon.jsx
Relevant case: Old Guadalupe Trail [in San Bruno Mountain Park]
Before: Generic pushpin icon
Now:
> Hiker icon for highway=path

- src/components/Itinerary.jsx
- src/components/ItineraryBikeLeg.jsx
- src/components/ItineraryHeader.jsx
- src/components/ItineraryTransitLeg.jsx
- src/components/RouteLeg.jsx
- src/components/RoutesOverview.jsx
- src/features/routes.js
- src/lib/TransitModes.js
- src/lib/formatMajorStreets.js
- src/lib/leg.js
PR to PR #324 implementing most of my feedback to that PR.
- Localizes the mode name labels by reusing code from RouteLeg
- Fully localizes the list of streets ("via Valencia Street, 14th Street")
- Removes useless use of async/await
- Removes unused viewingLeg member of routes reducer
- Fixes setState in render
- Allows expanding multiple legs at a time
- Misc cleanup
Not implemented because didn't seem blocking: Suggestion to use CSS to set the size (number of lines) of clamped alerts, using overflow: hidden and [text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow): ellipsis, instead of a character limit
> Fix more collapsible leg issues

- src/lib/urlMiddleware.js
We support overriding the locale like this (to get Spanish translations): `https://bikehopper.org/?locale=es-US`
Client-side routing should preserve that locale parameter, but it isn't preserving it in the case where a route fetch fails. This fixes.
> Fix URL router clearing locale

- src/features/routeParams.js
Usually, BikeHopper defaults to geolocating your start location when you enter an end location (or select an end location on the map).
This commit makes it so that after geolocation fails due to a permission denied error, we will no longer attempt to default to it. We will just leave the start location field blank in those cases and let you manually select.
We'll restore the behavior of defaulting to geolocating your start location after the page is reloaded or after geolocation is manually selected and succeeds.
Fixes #342
> After permission denied, don't default to geolocation

- src/lib/getFitBlob.js
I missed this bug somehow after my refactor.  Even though I tested locally via on a computer via mapping apps, the cycling computer itself did not seem to like what was pushed to prod.  Fixed it, tested on actual device.
> Add fix to properly access lat/lon for fit file encoding

- .eslintrc.cjs
- src/features/routeParams.js
Also: Fix some technically incorrect async action creators to not resolve before the underlying async action completes. I don't think this resulted in any visible bug as written.
> Lint: require async functions to use await

- src/features/routeParams.js
Fixes a bug where
1. You select a destination by right-click/long-press on map
2. Geolocating you takes a long time
3. In the meantime, you enter a manual start location
-> the eventual geolocated location would clobber the manual start location.
I thought I'd already fixed this, and I had, but not for the choose-on-map case.
> Fix bug where geolocation clobbers start point

- src/lib/colors.js
We display bike routes as dark gray (asphalt color) if there's no bike infrastructure on that street, and dark green if there's an off-street path or protected bike lane. Currently, those two colors are hard to distinguish:
This PR will make them a little easier to distinguish:
Fixes #120.
> Distinguish bike colors more

- vite.config.ts
this breaks our giant index.js into a few smaller files so they will be loaded in parallel. it should offer improved time to first paint because the data comes in faster while also improving out cache hit rate for these files because now turf and maplibre can be cached in a CDN and on device and will be reusable across deploys UI deploys so long as we dont change package versions. since we update these far less often than we update our own code this will basically halve the amount of data that needs to be downloaded for most page loads. 
There is more that could be done on this front, such as bundling other stuff that changes infrequently into its own files, targeting 500kb per file, and pointing our react and maplibre to external CDN versions so we can get cache hit from other sites. but …
> split out some big vendor modules into their own files

- .env.development.template
- docker-compose.yaml
- package.json
- vite.config.ts
To use the docker dev env you only need docker and git installed locally. git clone the the UI repo, cd into it, then run `docker compose up`. lastly open [https://localhost:3000/](https://localhost:3000/) in your browser. 
The vite "open" option that pops your browser open does not work in docker because of docker security model, the workarounds are ugly. If you still want a JS devX you can clone the repo and run `npm run start:dev` this just calls docker compose up but many JS dev, expect an `npm` based start up command. i think it is fine and we only use `npm` to call a script and i highly doubt the `npm` scripts API will change, so we don't really need to worry about what version of node/`npm` someone has installed. Since in theory all the node stuff happens in a container, which has …
> Add docker based dev env

- src/components/ItineraryHeader.css
- src/components/ItineraryHeader.tsx
This makes sure we don't show a colon unless there's both a header and a body. Addresses part of #258
> Transit alerts: omit colon if no body

- src/components/RoutesOverview.jsx
- src/features/routes.ts
In my experience watching people use BikeHopper, when they click on an itinerary other than the first one, they usually just want to highlight it on the map, and don't want to go into the detailed instructions screen.
This change makes it so that the first tap on an unselected itinerary just highlights it, while tapping on an already selected itinerary still goes into the instructions.
To hint that step-by-step instructions are available, a new bullet-point list icon is shown on the selected itinerary.
Default state:
After tapping once on second itinerary:
> 2 taps for instructions

- src/components/BikeHopperMap.tsx
This was tripping me up: while trying to adjust an end point, routes would get computed and I would lose my place in the map.
> Don't pan the map while dragging markers

- src/features/routeParams.ts
Purpose: Mitigate bad geocoding like in issue #230 where typing an address like "250 Howard Street" results in a generic result for just "Howard Street."
How it works today: If you click on a geocoded result from the dropdown, the input text gets replaced with a description of that geocoded result. But if you type something and hit Return, your typed text stays unchanged, giving no indication of what result was found.
What this commit changes: Typing something and hitting Return will also replace your input text with a description of the geocoded result.
Future work: Fix Photon not to return results at all if they fail to match part of what you typed (or flag such results as inexact). Get better address data into our geocoder.
> Update start/end input text to reflect geocoding

- compiled-lang/en.json
- lang/en.json
- package.json
We were not extracting strings from TypeScript files for translation. Note our sole, so far, .d.ts file breaks extraction; it seems FormatJS can't parse `declare module`.
> Fix FormatJS extraction of .ts files

- src/components/BikeHopperMap.tsx
The interactive layers we're querying such as inactiveLayer only exist when routes are displayed, and MapLibre was printing a warning in the console in dev mode about them not existing.
To fix, only query for features on those layers when routes are being displayed.
> Hide warning about querying layer not in map

- src/components/primitives/ModalDialog.tsx
The X to close a modal was invisible in dark mode due to applying color classes at the wrong level.
> fix X button in modal dialog in dark mode

- package-lock.json
- package.json
- src/components/BikeHopperMap.tsx
- src/components/InstructionIcon.tsx
- src/components/Itinerary.css
- src/components/Itinerary.tsx
- src/components/ItineraryBase.tsx
- src/components/ItineraryBikeLeg.tsx
- src/components/ItineraryBikeStep.tsx
- src/components/ItineraryRow.css
- src/components/ItineraryRow.tsx
- src/components/ItinerarySingleStep.tsx
- src/components/ItinerarySingleTransitStop.tsx
- src/components/ItineraryStep.css
- src/components/ItineraryStep.tsx
- src/components/ItineraryTimeline.tsx
- src/components/ItineraryTransitLeg.css
- src/components/ItineraryTransitLeg.tsx
- src/components/Routes.tsx
- src/features/routes.ts
- src/hooks/useScrollToRef.ts
- src/lib/BikeHopperClient.ts
- src/lib/alerts.ts
A usable view that allows you to step through each instruction step (for a bike leg) and each stop that a transit leg passes through.
Fixes #396
> Single step view

- src/components/BikeHopperMap.tsx
It opens OpenStreetMap.org in a new tab, useful for looking at how something is tagged - mostly only for us for development.
> "Open in OSM" in context menu

- src/hooks/useScreenDims.ts
This produces more reasonable results in my opinion... the sidebar is 400px wide, so the screen should have to be a bit more than twice that.
> Desktop/mobile layout: Switch at 900px not 750

- eslint.config.js
Having 'no-debugger' as an error means you're blocked from using the app in development when you place a debugger statement, which makes them unusable. Changing it to a warning will allow using them and make sure we remove them before commit.
> Lint: don't block dev when debugger statement added

- src/components/SearchDropdown.tsx
If you typed the exact, full string that an OSM point of interest renders as, it would not be shown (but any prefix of it worked fine).
> Fix bug: no autocomplete result for exact string

- src/components/SearchDropdown.tsx
- src/components/SearchDropdownGeocodeError.tsx
- src/features/geocoding.ts
Distinguishes between "There are no results for what you typed in"...
...and "Your connection is down" (or "The server errored," not shown):
In that case you can retry. Fixes #409
> Search: Link to retry geocoding

- src/components/App.tsx
- src/components/BikeHopperMap.tsx
- src/components/MobileMapLayout.tsx
Broken by desktop layout (#398): The controls were formerly updated upon a map load event, but that PR removed this.
Fixes #425
> Fix missing controls on mobile

- src/components/Itinerary.tsx
- src/components/RoutesOverview.tsx
- src/lib/BikeHopperClient.ts
- src/lib/time.ts
Fixes #125 
**Motivation:** 
- When browsing in another TZ, BH will interpret the value "Depart At" field as your system time, instead of SF local time
- As per [this issue comment](https://github.com/bikehopper/bikehopper-ui/issues/125#issuecomment-1114124135):
- in route results, all times should be displayed in Pacific Time
- "depart now" should mean now
- any specific time input as "depart at" or "arrive by" should be interpreted as Pacific Time
**Description of Changes:**
- Add timezone info to all components displaying departure/arrival time
- helper function to convert to local time
- grabs the offset (in minutes) of system time from UTC
-  calculates timezone offset of the current time in the  "America/Los_Angeles" locale
- compute the diff between the system time and pacific time …
> Use Bay Area Time for Time Picker

- eslint.config.js
- package-lock.json
- package.json
React-hooks-plugin now supports flat config without this adapter
> Deps cleanup: Remove @eslint/compat

- src/components/SelectionListItem.css
The Tailwind preflight handles most of the button reset but not text-align: left, leading to this glitch:
> Fix centered text in SelectionListItem

- src/lib/region.ts
To make development against a local bikehopper-web-app easier, this makes mapboxStyleUrl in the API-returned config completely optional in dev mode, and makes both mapboxStyleUrl and mapboxAccessToken optional if values are defined in env vars provided to bikehopper-ui.
(This will become moot after the mergening)
> Dev: make mapbox config items optional
